### ISSUE TITLE
Option to edit votes is not reliably available

### ISSUE THREAD

**Issue by a-kadlec** [EarlPitts/BadminBot#1]
The option to edit a vote in the poll is not always there. 
As of the poll on week#8, it has been absent right after making a vote, but it does seem to appear after visiting back much later.

Using firefox 110.0 (64-bit) on Windows 10 (for this test)
Also using 78.4.1esr (64-bit) from Debian, and from Ubuntu.

An example where (so far) it has been known to work reliably: https://strawpoll.com/polls/ajnEOO3RjZW
This uses the "Admin & Own votes" setting for edit permissions.

**Comment by EarlPitts** [comment]
Seems to be working now, I'm closing this.
